### ISSUE TITLE
[QUESTION] Asking for collaboration

### ISSUE THREAD

**Issue by raminjafary** [farnabaz/nuxt-dto#31]
Hi Ahad

I would like to make some improvements (project structure, update dependencies, APIs, etc.) and propose some features in case we both concur. If you are willing to accept any collaboration for further enhancements of the repo; Please let me know.

Thanks,

**Comment by farnabaz** [comment]
Hey
Nice to hear you :)
Sure contributions are more than welcome 👍

**Comment by raminjafary** [comment]
Thanks Ahad
