### ISSUE TITLE
[Feature] add debug mode

### ISSUE THREAD

**Issue by raminjafary** [farnabaz/nuxt-dto#39]
There are times one need to debug incoming responses or sent requests without additional setups. I think we can add something like a very simple debug option to conveniently allow logging responses or requests instead. What do you say?

```js
{
  modules: [
    ['nuxt-dto', {
      debug: true,
      handler: '/path/to/handler'
    }]
  ]
}
```

**Comment by farnabaz** [comment]
Hey @raminjafary :)
Sorry for the late response. I've missed the notif 🙁 

It looks good to me. Feel free to create PR for new features and bug fixs.

**Comment by raminjafary** [comment]
@farnabaz Thanks so much :)
